#!/bin/bash

#build the classpath
CLASSPATH=
for i in `find * -name "*.java"`
do
  CLASSPATH=${CLASSPATH}\ ${i}
done

if [ ! -d "bin" ]; then
	mkdir bin
fi

javac -d bin ${CLASSPATH} 

cd bin

#TODO
#Add arguments to program like framerate and etc.
java gui.UIController
